language: c

matrix:
  include:
    - os: linux
      dist: trusty
      env: BUILD_MODE=Debug
    - os: linux
      dist: trusty
      env: BUILD_MODE=RelWithDebInfo
    - os: linux
      dist: trusty
      env: BUILD_MODE=Release
    - os: osx
      env: BUILD_MODE=Debug
    - os: osx
      env: BUILD_MODE=RelWithDebInfo
    - os: osx
      env: BUILD_MODE=Release

script:
    - ./.travis_build_and_deploy.sh
