# version format
version: 1.0.{build}

branches:
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true
#skip_commits:
#  message: /ci skip/      # Regex for matching commit message

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\os-ioevents

platform:
  - x86
  - x64

build_script:
  - cmd: c:\projects\os-ioevents\scripts\appveyor-build.bat

deploy_script:
  - ps: powershell -executionpolicy bypass -File c:\projects\os-ioevents\scripts\appveyor-deploy.ps1
